name: LeetCode Sync

on:
  schedule:
    - cron: "0 0 * * *"   # every midnight UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Fetch and save LeetCode submissions
        run: |
          mkdir -p solutions
          python scripts/fetch_leetcode.py

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add solutions/
          git commit -m "chore: update LeetCode solutions" || echo "No changes to commit"
          git push
