name: LeetCode Sync

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day at midnight (UTC)
  workflow_dispatch:       # allows manual run

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install LeetCode CLI
        run: pip install leetcode-cli

      - name: Fetch LeetCode submissions
        run: |
          leetcode user -c ${{ secrets.LEETCODE_COOKIE }} > submissions/leetcode_dump.json

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add submissions/
          git commit -m "chore: update LeetCode submissions"
          git push
